export const locationData: Record<string, Record<string, string[]>> = {
  "India": {
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry", "Tirupati", "Kadapa", "Kakinada", "Anantapur"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Namsai", "Tawang"],
    "Assam": ["Guwahati", "Dibrugarh", "Silchar", "Jorhat", "Nagaon", "Tinsukia", "Tezpur"],
    "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Arrah", "Begusarai", "Katihar", "Munger"],
    "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Rajnandgaon", "Jagdalpur", "Ambikapur"],
    "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Junagadh", "Anand", "Navsari", "Morbi", "Vapi"],
    "Haryana": ["Faridabad", "Gurugram", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar", "Karnal", "Sonipat", "Panchkula"],
    "Himachal Pradesh": ["Shimla", "Dharamshala", "Solan", "Mandi", "Baddi", "Nahan"],
    "Jharkhand": ["Jamshedpur", "Ranchi", "Dhanbad", "Bokaro Steel City", "Deoghar", "Hazaribagh", "Giridih"],
    "Karnataka": ["Bangalore", "Hubli-Dharwad", "Mysore", "Belgaum", "Mangalore", "Gulbarga", "Davangere", "Bellary", "Shimoga", "Tumkur"],
    "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", "Thrissur", "Alappuzha", "Palakkad", "Kannur", "Kottayam"],
    "Madhya Pradesh": ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Dewas", "Satna", "Ratlam", "Rewa"],
    "Maharashtra": [
      "Mumbai", "Pune", "Nagpur", "Thane", "Pimpri-Chinchwad", "Nashik", "Kalyan-Dombivli", "Vasai-Virar", "Aurangabad", "Navi Mumbai", 
      "Solapur", "Mira-Bhayandar", "Bhiwandi", "Amravati", "Nanded", "Kolhapur", "Ulhasnagar", "Sangli", "Malegaon", "Jalgaon", 
      "Akola", "Latur", "Dhule", "Ahmednagar", "Chandrapur", "Parbhani", "Ichalkaranji", "Jalna", "Ambarnath", "Bhusawal", "Panvel"
    ],
    "Manipur": ["Imphal", "Thoubal", "Kakching"],
    "Meghalaya": ["Shillong", "Tura", "Jowai"],
    "Mizoram": ["Aizawl", "Lunglei", "Champhai"],
    "Nagaland": ["Dimapur", "Kohima", "Mokokchung"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore", "Bhadrak"],
    "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Hoshiarpur", "Mohali", "Pathankot"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur", "Bhilwara", "Alwar", "Sikar", "Bharatpur"],
    "Sikkim": ["Gangtok", "Namchi", "Geyzing"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Tiruppur", "Salem", "Erode", "Vellore", "Thoothukudi", "Nagercoil"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam", "Khammam", "Mahbubnagar"],
    "Tripura": ["Agartala", "Dharmanagar", "Udaipur"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Meerut", "Varanasi", "Allahabad", "Noida", "Greater Noida", "Bareilly", "Aligarh", "Moradabad", "Jhansi", "Gorakhpur", "Mathura"],
    "Uttarakhand": ["Dehradun", "Haridwar", "Haldwani", "Roorkee", "Rudrapur", "Kashipur"],
    "West Bengal": ["Kolkata", "Howrah", "Asansol", "Siliguri", "Durgapur", "Kharagpur", "Bardhaman", "English Bazar", "Baharampur", "Habra"],
    "Delhi": ["New Delhi", "North Delhi", "South Delhi", "West Delhi", "East Delhi", "Dwarka", "Rohini", "Saket"],
    "Jammu & Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla"],
    "Puducherry": ["Puducherry", "Karaikal", "Ozhukarai"]
  },
  "Netherlands": {
    "Drenthe": ["Assen", "Emmen", "Hoogeveen", "Coevorden", "Meppel"],
    "Flevoland": ["Almere", "Lelystad", "Dronten", "Urk", "Zeewolde"],
    "Friesland": ["Leeuwarden", "Drachten", "Sneek", "Heerenveen", "Harlingen"],
    "Gelderland": ["Arnhem", "Nijmegen", "Apeldoorn", "Ede", "Zutphen", "Doetinchem", "Harderwijk", "Tiel", "Wageningen"],
    "Groningen": ["Groningen", "Delfzijl", "Veendam", "Winschoten", "Stadskanaal"],
    "Limburg": ["Maastricht", "Venlo", "Sittard-Geleen", "Heerlen", "Roermond", "Weert", "Kerkrade"],
    "North Brabant": ["Eindhoven", "Tilburg", "Breda", "'s-Hertogenbosch", "Helmond", "Roosendaal", "Oss", "Bergen op Zoom", "Waalwijk"],
    "North Holland": ["Amsterdam", "Haarlem", "Zaanstad", "Haarlemmermeer", "Alkmaar", "Amstelveen", "Purmerend", "Hilversum", "Hoorn", "Den Helder"],
    "Overijssel": ["Enschede", "Zwolle", "Deventer", "Hengelo", "Almelo", "Kampen"],
    "South Holland": [
      "Rotterdam", "The Hague", "Zoetermeer", "Leiden", "Dordrecht", "Alphen aan den Rijn", "Delft", 
      "Schiedam", "Spijkenisse", "Gouda", "Vlaardingen", "Capelle aan den IJssel", "Katwijk"
    ],
    "Utrecht": ["Utrecht", "Amersfoort", "Veenendaal", "Zeist", "Nieuwegein", "Houten", "Woerden"],
    "Zeeland": ["Middelburg", "Vlissingen", "Goes", "Terneuzen"]
  },
  "Egypt": {
    "Alexandria": ["Alexandria", "Borg El Arab"],
    "Aswan": ["Aswan", "Kom Ombo", "Edfu", "Daraw"],
    "Asyut": ["Asyut", "Dairut", "Manfalut", "Aboub", "El Badari"],
    "Beheira": ["Damanhur", "Kafr El Dawwar", "Rashid", "Edku", "Abu Hummus"],
    "Beni Suef": ["Beni Suef", "Biba", "Nasser", "El Wasty"],
    "Cairo": ["Cairo", "Helwan", "New Cairo", "15th of May City", "El Shorouk", "Badr City"],
    "Dakahlia": ["Mansoura", "Mit Ghamr", "Talkha", "Senbellawein", "Dikirnis"],
    "Damietta": ["Damietta", "New Damietta", "Ras El Bar", "Faraskur"],
    "Faiyum": ["Faiyum", "Sinnuris", "Ibshaway", "Tsa"],
    "Gharbia": ["Tanta", "Mahalla El Kubra", "Zifta", "Kafr El Zayat", "Samanoud"],
    "Giza": ["Giza", "6th of October City", "Sheikh Zayed City", "Hawamdia", "Al Badrashein", "Atfih"],
    "Ismailia": ["Ismailia", "Fayed", "El Qantara", "El Tall El Kebir"],
    "Kafr El Sheikh": ["Kafr El Sheikh", "Desouk", "Metoubes", "Fuwwah", "Baltim"],
    "Luxor": ["Luxor", "Esna", "Armant"],
    "Matruh": ["Marsa Matruh", "Siwa", "El Alamein", "Dabaa"],
    "Minya": ["Minya", "Mallawi", "Beni Mazar", "Samalut", "Abu Qurqas"],
    "Monufia": ["Shibin El Kom", "Sadat City", "Ashmoun", "Menouf", "Quesna"],
    "New Valley": ["Kharga", "Dakhla", "Farafra", "Mut"],
    "North Sinai": ["Arish", "Sheikh Zuweid", "Rafah"],
    "Port Said": ["Port Said", "Port Fouad"],
    "Qalyubia": ["Banha", "Shubra El Kheima", "Qalyub", "Khanka", "Shebin El Qanater"],
    "Qena": ["Qena", "Nag Hammadi", "Qus", "Deshna", "Abu Tesht"],
    "Red Sea": ["Hurghada", "Safaga", "El Gouna", "Marsa Alam", "Quseir", "Ras Gharib"],
    "Sharqia": ["Zagazig", "10th of Ramadan City", "Bilbeis", "Minya El Qamh", "Faqous"],
    "Sohag": ["Sohag", "Girga", "Akhmim", "Tahta", "Tima"],
    "South Sinai": ["Sharm El Sheikh", "Dahab", "Nuweiba", "Tor Sinai", "Ras Sudr"],
    "Suez": ["Suez"]
  }
};
